### PR TITLE
Bepu Navigation fixes

### PR DESCRIPTION
**Pull request by Doprez**
# PR Details

This is meant to make the usability of the navigation library more user friendly. 

- Add the ability to forace calculate a path with `TryFindPath`
- Made methods to keep following the path even when looking for a new one (up to the user)
- Created state enum to give better info on the path planning results

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Doprez** [comment]
I think the clean up part is done, I just need to update the demo and make sure things work like I expect them to.

**Comment by Eideren** [comment]
Thanks !
Sounds like there's a fair amount of things that could be improved, but looks good for now. A couple of things to keep in mind if you haven't:

`Update()`
- I'm guessing it will be common for users to overwrite this method, best make it extra clear it is called in parallel.
- instead of having the `IsMoving` check inside, we could have `IsMoving` add the component to a collection in the processor, then the processor calls update over all of the items contained within that collection. Remember that dispatcher works best when each work item takes around the same amount of time. Having a bunch of them effectively no-op by failing the `IsMoving` may create unexpected timings where certain threads have a lot more work to chew through while others are effectively idle. It's not always possible to ensure that this would be the case, but here it seems fairly trivial to setup.

`Move()`
- You get the position in world space but write to its local space. Do use `position = Vector3.MoveTo(position, nextWaypointPosition, Speed * deltaTime)` and then check `position == nextWaypointPosition` to remove from the path, that way there is no weird epsilon test (who knows what scale users are actually using, `0.1` might be too large) and you can remove it from the path right then and there instead of having a one frame delay.
- For the physics one you can re-use the code but using the physics delta time multiplied by the character component's speed instead. Then take the direction to plug it in the move function like you're doing there. Looking at how the two are structured there also hints at how users may want to customize this logic, perhaps making that specific scope virtual instead of making `Update()` virtual is more appropriate ?

`Rotate()`
- Rotation there is set in local spacefor physics here, `PhysicsComponent.Orientation` already sets `Entity.Transform.Rotation`
`NavigationState`:
- Should be its own file, like we do with most enums in the rest of the engine

**Comment by Doprez** [comment]
>You get the position in world space but write to its local space. Do use position = Vector3.MoveTo(position, nextWaypointPosition, Speed * deltaTime) and then check position == nextWaypointPosition to remove from the path, that way there is no weird epsilon test (who knows what scale users are actually using, 0.1 might be too large) and you can remove it from the path right then and there instead of having a one frame delay.

Ill have to look into this carefully, I think the reason I did it this way was for the physics mover since it wasnt the right Y axis of the path position so it would never be true. I do fully agree with what you are saying though, it makes sense.

> Looking at how the two are structured there also hints at how users may want to customize this logic, perhaps making that specific scope virtual instead of making Update() virtual is more appropriate ?

So make the `Move` function virtual instead of `Update` you mean?

the rest I think makes sense and I can take a look at it either this weekend or next weekend.

**Comment by Eideren** [comment]
> So make the `Move` function virtual instead of `Update` you mean?

Not quite, something higher level than that which takes the next destination as argument and outputs true if whatever is moving reached the destination;
```cs
private void PathEvaluation(float deltaTime)
{
	if (waypointIndex >= Path.Count)
	{
		State = NavigationState.PathIsInvalid;
		return;
	}

	ParallelMove(Path[waypointIndex], out bool reachedDestination);
	if (reachedDestination)
		waypointIndex++;
}

protected virtual void ParallelMove(Vector3 destination, out bool reachedDestination)
{
	float angle = (float)Math.Atan2(destination.Z - position.Z, destination.X - position.X);
	Entity.Transform.Rotation = Quaternion.RotationY(-angle);
	Entity.Transform.Position = Vector3.MoveTo(Entity.Transform.Position, destination, Speed * deltaTime);
	reachedDestination = Entity.Transform.Position == destination;
}
```
Meh, `Move` itself is fairly easy to write, so I'll leave it in your hands, do whatever feels right to you

**Pull request merged**
